image: java:8-jdk
stages:
  - build
before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build:
  stage: build
  script:
    - sudo bash "./gradlew -DpublishDocs.root=/var/www/docs/sliced build publish publishDocs --info --no-daemon"
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  only:
    - master
  tags:
    - linux
